import type {
  BoardConfig,
  BoardTile,
  EffectDescriptor,
} from "../schema";

const workEffects = [
  {
    type: "modifyResource",
    resource: "energy",
    amount: -1,
    clampAtZero: true,
  },
  {
    type: "incrementWorkCounter",
    amount: 1,
    rewardEvery: 5,
    reward: { resource: "reputation", amount: 1 },
    cumulative: true,
  },
  { type: "drawCards", deckId: "deck.work", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const meetingEffects = [
  { type: "drawCards", deckId: "deck.meeting", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const eventEffects = [
  { type: "drawCards", deckId: "deck.event", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const networkingEffects = [
  { type: "drawCards", deckId: "deck.networking", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const restoreEnergyEffects = [
  { type: "restoreResourceToMaximum", resource: "energy" },
] as const satisfies readonly EffectDescriptor[];

const spaces = [
  {
    id: "tile.board.00.receptionist",
    index: 0,
    placement: "corner",
    coordinate: "bottom-right",
    kind: "receptionist",
    displayNameKey: "deadlineDash.board.tile.receptionist.name",
    effects: [
      { type: "gainSalary", trigger: "pass" },
      { type: "gainSalary", trigger: "land" },
      { type: "grantExtraRoll", count: 1 },
    ],
  },
  {
    id: "tile.board.01.finance",
    index: 1,
    placement: "side",
    side: "bottom",
    coordinate: 10,
    kind: "finance",
    displayNameKey: "deadlineDash.board.tile.finance.name",
    effects: [
      {
        type: "payResource",
        resource: "money",
        amount: 300,
        insufficientFunds: "pay-up-to-available",
      },
    ],
  },
  {
    id: "tile.board.02.pantry",
    index: 2,
    placement: "side",
    side: "bottom",
    coordinate: 9,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.pantry.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.03.meeting-bottom",
    index: 3,
    placement: "side",
    side: "bottom",
    coordinate: 8,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.04.work-bottom-4",
    index: 4,
    placement: "side",
    side: "bottom",
    coordinate: 7,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.05.work-bottom-3",
    index: 5,
    placement: "side",
    side: "bottom",
    coordinate: 6,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.06.hr",
    index: 6,
    placement: "side",
    side: "bottom",
    coordinate: 5,
    kind: "hr",
    displayNameKey: "deadlineDash.board.tile.hr.name",
    effects: [
      {
        type: "rollCheck",
        dice: { count: 2, sides: 6 },
        rerollEligible: false,
        outcomes: [
          { when: { doubles: true }, effects: [] },
          {
            when: { doubles: false },
            effects: [
              {
                type: "modifyResource",
                resource: "reputation",
                amount: -1,
                clampAtZero: true,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "tile.board.07.coffee-machine",
    index: 7,
    placement: "side",
    side: "bottom",
    coordinate: 4,
    kind: "networking",
    displayNameKey: "deadlineDash.board.tile.coffeeMachine.name",
    effects: networkingEffects,
  },
  {
    id: "tile.board.08.work-bottom-2",
    index: 8,
    placement: "side",
    side: "bottom",
    coordinate: 3,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.09.work-bottom-1",
    index: 9,
    placement: "side",
    side: "bottom",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.10.training",
    index: 10,
    placement: "side",
    side: "bottom",
    coordinate: 1,
    kind: "training",
    displayNameKey: "deadlineDash.board.tile.training.name",
    effects: [
      {
        type: "rollCheck",
        dice: { count: 2, sides: 6 },
        rerollEligible: false,
        outcomes: [
          {
            when: { total: [2, 6] },
            effects: [
              { type: "modifyResource", resource: "reputation", amount: 1 },
            ],
          },
          {
            when: { total: [7, 12] },
            effects: [
              { type: "modifyResource", resource: "reputation", amount: 2 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "tile.board.11.board-meeting",
    index: 11,
    placement: "corner",
    coordinate: "bottom-left",
    kind: "board-meeting",
    displayNameKey: "deadlineDash.board.tile.boardMeeting.name",
    effects: [
      { type: "drawCards", deckId: "deck.board-meeting", count: 1 },
    ],
  },
  {
    id: "tile.board.12.burnout",
    index: 12,
    placement: "side",
    side: "left",
    coordinate: 10,
    kind: "burnout",
    displayNameKey: "deadlineDash.board.tile.burnout.name",
    effects: [{ type: "skipTurns", count: 2, source: "tile" }],
  },
  {
    id: "tile.board.13.work-left-2",
    index: 13,
    placement: "side",
    side: "left",
    coordinate: 9,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.14.ceo-office",
    index: 14,
    placement: "side",
    side: "left",
    coordinate: 8,
    kind: "ceo-office",
    displayNameKey: "deadlineDash.board.tile.ceoOffice.name",
    effects: [{ type: "attemptPromotion" }],
  },
  {
    id: "tile.board.15.smoking-area",
    index: 15,
    placement: "side",
    side: "left",
    coordinate: 7,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.smokingArea.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.16.event-left",
    index: 16,
    placement: "side",
    side: "left",
    coordinate: 6,
    kind: "event",
    displayNameKey: "deadlineDash.board.tile.event.name",
    effects: eventEffects,
  },
  {
    id: "tile.board.17.ceo-favorite",
    index: 17,
    placement: "side",
    side: "left",
    coordinate: 5,
    kind: "ceo-favorite",
    displayNameKey: "deadlineDash.board.tile.ceoFavorite.name",
    effects: [
      { type: "modifyResource", resource: "reputation", amount: 2 },
    ],
  },
  {
    id: "tile.board.18.sales",
    index: 18,
    placement: "side",
    side: "left",
    coordinate: 4,
    kind: "sales",
    displayNameKey: "deadlineDash.board.tile.sales.name",
    effects: [
      {
        type: "rollCheck",
        dice: { count: 2, sides: 6 },
        rerollEligible: false,
        outcomes: [
          {
            when: { total: [2, 9] },
            effects: [
              {
                type: "applyStatus",
                statusId: "status.next-salary-multiplier",
                duration: { kind: "uses", count: 1 },
                parameters: { multiplier: 1.5 },
              },
            ],
          },
          {
            when: { total: [10, 12] },
            effects: [
              {
                type: "applyStatus",
                statusId: "status.next-salary-multiplier",
                duration: { kind: "uses", count: 1 },
                parameters: { multiplier: 2 },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "tile.board.19.meeting-left",
    index: 19,
    placement: "side",
    side: "left",
    coordinate: 3,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.20.work-left-1",
    index: 20,
    placement: "side",
    side: "left",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.21.best-employee",
    index: 21,
    placement: "side",
    side: "left",
    coordinate: 1,
    kind: "best-employee",
    displayNameKey: "deadlineDash.board.tile.bestEmployee.name",
    effects: [
      { type: "modifyResource", resource: "money", amount: 500 },
      { type: "modifyResource", resource: "reputation", amount: 3 },
    ],
  },
  {
    id: "tile.board.22.audit",
    index: 22,
    placement: "corner",
    coordinate: "top-left",
    kind: "audit",
    displayNameKey: "deadlineDash.board.tile.audit.name",
    effects: [
      {
        type: "auditConfinement",
        release: {
          roll: { count: 2, sides: 6 },
          requiresTrueDoubles: true,
          rerollEligible: false,
          alternativeFine: 500,
        },
      },
    ],
  },
  {
    id: "tile.board.23.operation",
    index: 23,
    placement: "side",
    side: "top",
    coordinate: 10,
    kind: "operation",
    displayNameKey: "deadlineDash.board.tile.operation.name",
    effects: [
      {
        type: "applyStatus",
        statusId: "status.next-roll-extra-movement",
        duration: { kind: "uses", count: 1 },
        parameters: { spaces: 2, traversal: true },
      },
    ],
  },
  {
    id: "tile.board.24.work-top-4",
    index: 24,
    placement: "side",
    side: "top",
    coordinate: 9,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.25.employee-lounge",
    index: 25,
    placement: "side",
    side: "top",
    coordinate: 8,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.employeeLounge.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.26.seminar",
    index: 26,
    placement: "side",
    side: "top",
    coordinate: 7,
    kind: "networking",
    displayNameKey: "deadlineDash.board.tile.seminar.name",
    effects: networkingEffects,
  },
  {
    id: "tile.board.27.work-top-3",
    index: 27,
    placement: "side",
    side: "top",
    coordinate: 6,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.28.legal",
    index: 28,
    placement: "side",
    side: "top",
    coordinate: 5,
    kind: "legal",
    displayNameKey: "deadlineDash.board.tile.legal.name",
    effects: [
      {
        type: "applyStatus",
        statusId: "status.skip-next-tile-effect",
        duration: { kind: "uses", count: 1 },
      },
    ],
  },
  {
    id: "tile.board.29.event-top",
    index: 29,
    placement: "side",
    side: "top",
    coordinate: 4,
    kind: "event",
    displayNameKey: "deadlineDash.board.tile.event.name",
    effects: eventEffects,
  },
  {
    id: "tile.board.30.meeting-top",
    index: 30,
    placement: "side",
    side: "top",
    coordinate: 3,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.31.work-top-2",
    index: 31,
    placement: "side",
    side: "top",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.32.work-top-1",
    index: 32,
    placement: "side",
    side: "top",
    coordinate: 1,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.33.annual-event",
    index: 33,
    placement: "corner",
    coordinate: "top-right",
    kind: "annual-event",
    displayNameKey: "deadlineDash.board.tile.annualEvent.name",
    effects: [
      { type: "drawCards", deckId: "deck.annual-event", count: 1 },
    ],
  },
  {
    id: "tile.board.34.work-right-4",
    index: 34,
    placement: "side",
    side: "right",
    coordinate: 10,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.35.office-gossip",
    index: 35,
    placement: "side",
    side: "right",
    coordinate: 9,
    kind: "networking",
    displayNameKey: "deadlineDash.board.tile.officeGossip.name",
    effects: networkingEffects,
  },
  {
    id: "tile.board.36.lunch-break",
    index: 36,
    placement: "side",
    side: "right",
    coordinate: 8,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.lunchBreak.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.37.marketing",
    index: 37,
    placement: "side",
    side: "right",
    coordinate: 7,
    kind: "marketing",
    displayNameKey: "deadlineDash.board.tile.marketing.name",
    effects: [
      { type: "modifyResource", resource: "reputation", amount: 1 },
    ],
  },
  {
    id: "tile.board.38.work-right-3",
    index: 38,
    placement: "side",
    side: "right",
    coordinate: 6,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.39.event-right",
    index: 39,
    placement: "side",
    side: "right",
    coordinate: 5,
    kind: "event",
    displayNameKey: "deadlineDash.board.tile.event.name",
    effects: eventEffects,
  },
  {
    id: "tile.board.40.it",
    index: 40,
    placement: "side",
    side: "right",
    coordinate: 4,
    kind: "it",
    displayNameKey: "deadlineDash.board.tile.it.name",
    effects: [
      {
        type: "applyStatus",
        statusId: "status.ignore-next-work-energy",
        duration: { kind: "uses", count: 1 },
      },
    ],
  },
  {
    id: "tile.board.41.meeting-right",
    index: 41,
    placement: "side",
    side: "right",
    coordinate: 3,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.42.work-right-2",
    index: 42,
    placement: "side",
    side: "right",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.43.work-right-1",
    index: 43,
    placement: "side",
    side: "right",
    coordinate: 1,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
] as const satisfies readonly BoardTile[];

export const deadlineDashBoard = {
  id: "board.deadline-dash",
  direction: "clockwise",
  startIndex: 0,
  spaces,
  expectedCounts: {
    total: 44,
    corners: 4,
    regular: 40,
    perSide: 10,
    byKind: {
      receptionist: 1,
      "board-meeting": 1,
      audit: 1,
      "annual-event": 1,
      training: 1,
      work: 14,
      networking: 3,
      hr: 1,
      meeting: 4,
      "energy-restore": 4,
      finance: 1,
      it: 1,
      event: 3,
      marketing: 1,
      legal: 1,
      operation: 1,
      "best-employee": 1,
      sales: 1,
      "ceo-favorite": 1,
      "ceo-office": 1,
      burnout: 1,
    },
  },
  sourceNotes: [
    "Indexes follow clockwise movement from Receptionist at the bottom-right corner.",
    "Side coordinates preserve the one-based numbering and printed direction of each GDD side table, so coordinates descend while traversing clockwise.",
    "All 14 Work spaces draw a Work card per the accepted rules baseline, including GDD rows whose short effect text omits the draw.",
    "Receptionist pass and landing salary are separate triggers; landing also grants one extra roll.",
  ],
} as const satisfies BoardConfig;
