import type {
  BoardConfig,
  BoardTile,
  EffectDescriptor,
} from "../schema";

const workEffects = [
  {
    type: "modifyResource",
    resource: "energy",
    amount: -1,
    clampAtZero: true,
  },
  {
    type: "incrementWorkCounter",
    amount: 1,
    rewardEvery: 5,
    reward: { resource: "reputation", amount: 1 },
    cumulative: true,
  },
  { type: "drawCards", deckId: "deck.work", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const meetingEffects = [
  { type: "drawCards", deckId: "deck.meeting", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const eventEffects = [
  { type: "drawCards", deckId: "deck.event", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const networkingEffects = [
  { type: "drawCards", deckId: "deck.networking", count: 1 },
] as const satisfies readonly EffectDescriptor[];

const restoreEnergyEffects = [
  { type: "restoreResourceToMaximum", resource: "energy" },
] as const satisfies readonly EffectDescriptor[];

/**
 * Board order is the design workbook's own ordering, read straight off
 * `01_Board_Corners` and `02_General_Tiles`:
 *
 *   board index = 11 * (side - 1) + coordinate,  corners at 11 * (corner - 1)
 *
 * so `coordinate` is the workbook's `side,index` ordinal and **ascends** in the
 * direction of travel. Corner 1 (Receptionist) is index 0, corner 2 (Board
 * Meeting) 11, corner 3 (Audit) 22, corner 4 (Company Annual Event) 33, and
 * each ten-tile block between two corners is one workbook side in workbook
 * order.
 */
const spaces = [
  {
    id: "tile.board.00.receptionist",
    index: 0,
    placement: "corner",
    coordinate: "bottom-right",
    kind: "receptionist",
    displayNameKey: "deadlineDash.board.tile.receptionist.name",
    effects: [
      { type: "gainSalary", trigger: "pass" },
      { type: "gainSalary", trigger: "land" },
      { type: "grantExtraRoll", count: 1 },
    ],
  },
  {
    id: "tile.board.01.training",
    index: 1,
    placement: "side",
    side: "bottom",
    coordinate: 1,
    kind: "training",
    displayNameKey: "deadlineDash.board.tile.training.name",
    // Nothing happens automatically here: the whole tile is the decision below.
    effects: [],
    decision: {
      kind: "training-course",
      accept: {
        optionId: "enroll",
        cost: { resource: "money", amount: 300 },
        roll: { count: 2, sides: 6 },
        rerollEligible: false,
        outcomes: [
          {
            when: { total: [2, 6] },
            effects: [
              { type: "modifyResource", resource: "reputation", amount: 2 },
            ],
          },
          {
            when: { total: [7, 12] },
            effects: [
              { type: "modifyResource", resource: "reputation", amount: 3 },
            ],
          },
        ],
      },
      decline: {
        optionId: "decline",
        effects: [
          { type: "modifyResource", resource: "reputation", amount: 1 },
        ],
      },
      whenUnaffordable: "resolve-decline",
    },
  },
  {
    id: "tile.board.02.work-bottom-1",
    index: 2,
    placement: "side",
    side: "bottom",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.03.work-bottom-2",
    index: 3,
    placement: "side",
    side: "bottom",
    coordinate: 3,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.04.coffee-machine",
    index: 4,
    placement: "side",
    side: "bottom",
    coordinate: 4,
    kind: "networking",
    displayNameKey: "deadlineDash.board.tile.coffeeMachine.name",
    effects: networkingEffects,
  },
  {
    id: "tile.board.05.hr",
    index: 5,
    placement: "side",
    side: "bottom",
    coordinate: 5,
    kind: "hr",
    displayNameKey: "deadlineDash.board.tile.hr.name",
    effects: [
      {
        type: "rollCheck",
        dice: { count: 2, sides: 6 },
        rerollEligible: false,
        outcomes: [
          { when: { doubles: true }, effects: [] },
          {
            when: { doubles: false },
            effects: [
              {
                type: "modifyResource",
                resource: "reputation",
                amount: -1,
                clampAtZero: true,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "tile.board.06.work-bottom-3",
    index: 6,
    placement: "side",
    side: "bottom",
    coordinate: 6,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.07.work-bottom-4",
    index: 7,
    placement: "side",
    side: "bottom",
    coordinate: 7,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.08.meeting-bottom",
    index: 8,
    placement: "side",
    side: "bottom",
    coordinate: 8,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.09.pantry",
    index: 9,
    placement: "side",
    side: "bottom",
    coordinate: 9,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.pantry.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.10.finance",
    index: 10,
    placement: "side",
    side: "bottom",
    coordinate: 10,
    kind: "finance",
    displayNameKey: "deadlineDash.board.tile.finance.name",
    effects: [
      {
        type: "payResource",
        resource: "money",
        amount: 300,
        insufficientFunds: "pay-up-to-available",
      },
    ],
  },
  {
    id: "tile.board.11.board-meeting",
    index: 11,
    placement: "corner",
    coordinate: "bottom-left",
    kind: "board-meeting",
    displayNameKey: "deadlineDash.board.tile.boardMeeting.name",
    effects: [
      { type: "drawCards", deckId: "deck.board-meeting", count: 1 },
    ],
  },
  {
    id: "tile.board.12.work-left-1",
    index: 12,
    placement: "side",
    side: "left",
    coordinate: 1,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.13.work-left-2",
    index: 13,
    placement: "side",
    side: "left",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.14.meeting-left",
    index: 14,
    placement: "side",
    side: "left",
    coordinate: 3,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.15.it",
    index: 15,
    placement: "side",
    side: "left",
    coordinate: 4,
    kind: "it",
    displayNameKey: "deadlineDash.board.tile.it.name",
    effects: [
      {
        type: "applyStatus",
        statusId: "status.ignore-next-work-energy",
        duration: { kind: "uses", count: 1 },
      },
    ],
  },
  {
    id: "tile.board.16.event-left",
    index: 16,
    placement: "side",
    side: "left",
    coordinate: 5,
    kind: "event",
    displayNameKey: "deadlineDash.board.tile.event.name",
    effects: eventEffects,
  },
  {
    id: "tile.board.17.work-left-3",
    index: 17,
    placement: "side",
    side: "left",
    coordinate: 6,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.18.marketing",
    index: 18,
    placement: "side",
    side: "left",
    coordinate: 7,
    kind: "marketing",
    displayNameKey: "deadlineDash.board.tile.marketing.name",
    effects: [
      { type: "modifyResource", resource: "reputation", amount: 1 },
    ],
  },
  {
    id: "tile.board.19.lunch-break",
    index: 19,
    placement: "side",
    side: "left",
    coordinate: 8,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.lunchBreak.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.20.office-gossip",
    index: 20,
    placement: "side",
    side: "left",
    coordinate: 9,
    kind: "networking",
    displayNameKey: "deadlineDash.board.tile.officeGossip.name",
    effects: networkingEffects,
  },
  {
    id: "tile.board.21.work-left-4",
    index: 21,
    placement: "side",
    side: "left",
    coordinate: 10,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.22.audit",
    index: 22,
    placement: "corner",
    coordinate: "top-left",
    kind: "audit",
    displayNameKey: "deadlineDash.board.tile.audit.name",
    effects: [
      {
        type: "auditConfinement",
        release: {
          roll: { count: 2, sides: 6 },
          requiresTrueDoubles: true,
          rerollEligible: false,
          alternativeFine: 500,
        },
      },
    ],
  },
  {
    id: "tile.board.23.work-top-1",
    index: 23,
    placement: "side",
    side: "top",
    coordinate: 1,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.24.work-top-2",
    index: 24,
    placement: "side",
    side: "top",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.25.meeting-top",
    index: 25,
    placement: "side",
    side: "top",
    coordinate: 3,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.26.event-top",
    index: 26,
    placement: "side",
    side: "top",
    coordinate: 4,
    kind: "event",
    displayNameKey: "deadlineDash.board.tile.event.name",
    effects: eventEffects,
  },
  {
    id: "tile.board.27.legal",
    index: 27,
    placement: "side",
    side: "top",
    coordinate: 5,
    kind: "legal",
    displayNameKey: "deadlineDash.board.tile.legal.name",
    effects: [
      {
        type: "applyStatus",
        statusId: "status.skip-next-tile-effect",
        duration: { kind: "uses", count: 1 },
      },
    ],
  },
  {
    id: "tile.board.28.work-top-3",
    index: 28,
    placement: "side",
    side: "top",
    coordinate: 6,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.29.seminar",
    index: 29,
    placement: "side",
    side: "top",
    coordinate: 7,
    kind: "networking",
    displayNameKey: "deadlineDash.board.tile.seminar.name",
    effects: networkingEffects,
  },
  {
    id: "tile.board.30.employee-lounge",
    index: 30,
    placement: "side",
    side: "top",
    coordinate: 8,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.employeeLounge.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.31.work-top-4",
    index: 31,
    placement: "side",
    side: "top",
    coordinate: 9,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.32.operation",
    index: 32,
    placement: "side",
    side: "top",
    coordinate: 10,
    kind: "operation",
    displayNameKey: "deadlineDash.board.tile.operation.name",
    effects: [
      {
        type: "applyStatus",
        statusId: "status.next-roll-extra-movement",
        duration: { kind: "uses", count: 1 },
        parameters: { spaces: 2, traversal: true },
      },
    ],
  },
  {
    id: "tile.board.33.annual-event",
    index: 33,
    placement: "corner",
    coordinate: "top-right",
    kind: "annual-event",
    displayNameKey: "deadlineDash.board.tile.annualEvent.name",
    effects: [
      { type: "drawCards", deckId: "deck.annual-event", count: 1 },
    ],
  },
  {
    id: "tile.board.34.best-employee",
    index: 34,
    placement: "side",
    side: "right",
    coordinate: 1,
    kind: "best-employee",
    displayNameKey: "deadlineDash.board.tile.bestEmployee.name",
    effects: [
      { type: "modifyResource", resource: "money", amount: 500 },
      { type: "modifyResource", resource: "reputation", amount: 3 },
    ],
  },
  {
    id: "tile.board.35.work-right-1",
    index: 35,
    placement: "side",
    side: "right",
    coordinate: 2,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.36.meeting-right",
    index: 36,
    placement: "side",
    side: "right",
    coordinate: 3,
    kind: "meeting",
    displayNameKey: "deadlineDash.board.tile.meeting.name",
    effects: meetingEffects,
  },
  {
    id: "tile.board.37.sales",
    index: 37,
    placement: "side",
    side: "right",
    coordinate: 4,
    kind: "sales",
    displayNameKey: "deadlineDash.board.tile.sales.name",
    effects: [
      {
        type: "rollCheck",
        dice: { count: 2, sides: 6 },
        rerollEligible: false,
        outcomes: [
          {
            when: { total: [2, 9] },
            effects: [
              {
                type: "applyStatus",
                statusId: "status.next-salary-multiplier",
                duration: { kind: "uses", count: 1 },
                parameters: { multiplier: 1.5 },
              },
            ],
          },
          {
            when: { total: [10, 12] },
            effects: [
              {
                type: "applyStatus",
                statusId: "status.next-salary-multiplier",
                duration: { kind: "uses", count: 1 },
                parameters: { multiplier: 2 },
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "tile.board.38.ceo-favorite",
    index: 38,
    placement: "side",
    side: "right",
    coordinate: 5,
    kind: "ceo-favorite",
    displayNameKey: "deadlineDash.board.tile.ceoFavorite.name",
    effects: [
      { type: "modifyResource", resource: "reputation", amount: 2 },
    ],
  },
  {
    id: "tile.board.39.event-right",
    index: 39,
    placement: "side",
    side: "right",
    coordinate: 6,
    kind: "event",
    displayNameKey: "deadlineDash.board.tile.event.name",
    effects: eventEffects,
  },
  {
    id: "tile.board.40.smoking-area",
    index: 40,
    placement: "side",
    side: "right",
    coordinate: 7,
    kind: "energy-restore",
    displayNameKey: "deadlineDash.board.tile.smokingArea.name",
    effects: restoreEnergyEffects,
  },
  {
    id: "tile.board.41.ceo-office",
    index: 41,
    placement: "side",
    side: "right",
    coordinate: 8,
    kind: "ceo-office",
    displayNameKey: "deadlineDash.board.tile.ceoOffice.name",
    effects: [{ type: "attemptPromotion" }],
  },
  {
    id: "tile.board.42.work-right-2",
    index: 42,
    placement: "side",
    side: "right",
    coordinate: 9,
    kind: "work",
    displayNameKey: "deadlineDash.board.tile.work.name",
    effects: workEffects,
  },
  {
    id: "tile.board.43.burnout",
    index: 43,
    placement: "side",
    side: "right",
    coordinate: 10,
    kind: "burnout",
    displayNameKey: "deadlineDash.board.tile.burnout.name",
    effects: [
      { type: "skipTurns", count: 2, source: "tile" },
      // Coming back from burnout leave is not instantaneous: the two skipped
      // turns are followed by two of the player's own turns spent dragging,
      // one space short on every roll. This is the only turns-duration status
      // in the pack; every other status is consumed by uses.
      {
        type: "applyStatus",
        statusId: "status.burnout-tile",
        duration: { kind: "turns", count: 2 },
        parameters: { movementPenalty: 1 },
      },
    ],
  },
] as const satisfies readonly BoardTile[];

export const deadlineDashBoard = {
  id: "board.deadline-dash",
  direction: "clockwise",
  startIndex: 0,
  spaces,
  expectedCounts: {
    total: 44,
    corners: 4,
    regular: 40,
    perSide: 10,
    byKind: {
      receptionist: 1,
      "board-meeting": 1,
      audit: 1,
      "annual-event": 1,
      training: 1,
      work: 14,
      networking: 3,
      hr: 1,
      meeting: 4,
      "energy-restore": 4,
      finance: 1,
      it: 1,
      event: 3,
      marketing: 1,
      legal: 1,
      operation: 1,
      "best-employee": 1,
      sales: 1,
      "ceo-favorite": 1,
      "ceo-office": 1,
      burnout: 1,
    },
  },
  sourceNotes: [
    "Indexes follow clockwise movement from Receptionist at the bottom-right corner.",
    "Board order is the design workbook's ordering column, which the user declared authoritative: board index = 11 * (side - 1) + coordinate, corners at 11 * (corner - 1). Side coordinates are the workbook's own one-based side ordinal and therefore ASCEND while traversing clockwise.",
    // Kept deliberately, not deleted: this records the rationale the ordering
    // above replaced, and the source conflict it resolves.
    "SUPERSEDED RATIONALE (do not restore without a new decision): side coordinates used to descend while traversing clockwise, because each GDD side table was read as printed in the reverse of play order. Under that reading GDD section 4's edge names held - workbook side 2 on the physical RIGHT edge, side 4 on the LEFT, so the Burnout tile sat on the left as GDD line 840 states. The workbook's ordering column puts side 2 between Board Meeting and Audit (the LEFT edge) and side 4 between Annual Event and Receptionist (the RIGHT edge), so Burnout now renders on the RIGHT and the GDD's Sisi Kanan / Sisi Kiri labels and line 840 are stale prose. The workbook won by explicit user decision; the GDD is also internally inconsistent here, since its side-table arrows trace a counter-clockwise loop while GDD line 95 states movement is clockwise.",
    "All 14 Work spaces draw a Work card per the accepted rules baseline, including GDD rows whose short effect text omits the draw.",
    "Receptionist pass and landing salary are separate triggers; landing also grants one extra roll.",
  ],
} as const satisfies BoardConfig;
